### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by twurman** [twurman/clarityeco#13]
We have a lot of branches that are unused/behind the game. Which ones can I get rid of? The clarityinc_dev branch reflects the current state of the clarityinc repo plus my command center pr changes. Can I delete the cc branch, as well as the dev branch?

**Comment by twurman** [comment]
@llotneb @cdmeister

**Comment by llotneb** [comment]
Unless @cdmeister objects, I'd say go ahead. I haven't used cc lately, and I didn't see anything critical on dev when I checked this morning. If we're planning to use clarityinc_dev as our new dev branch, then maybe we should rename it too.

**Comment by cdmeister** [comment]
I don't mind.

**Comment by llotneb** [comment]
I renamed clarityeco_dev --> dev, and deleted the old dev branch.
